// ─── Copilot Service ──────────────────────────────────────────────────────────
// All insights are generated by the Agent Server (Claude Haiku).

import type { HomeStats } from '@/types'

export interface PageContext { currentPage: string }

export interface DashboardInsight {
  id: string; title: string; body: string;
  type: 'alert' | 'opportunity' | 'trend';
  priority: 'high' | 'medium' | 'low'; question: string;
}

export interface CRMStats {
  total: number; byStage: Record<string, number>;
  bySource: Record<string, number>; topTags: { name: string; count: number }[];
}

export interface CampaignInsight {
  id: string; title: string; body: string;
  type: 'alert' | 'opportunity' | 'trend' | 'success';
  priority: 'high' | 'medium' | 'low'; action: string;
}

const AGENT_URL = import.meta.env.VITE_AGENT_SERVER_URL ?? 'http://localhost:3002'

import axios from 'axios'

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:3000/api'

let _insightTokenCache: { token: string; expiresAt: number } | null = null
async function getAgentToken(): Promise<string> {
  if (_insightTokenCache && Date.now() < _insightTokenCache.expiresAt - 3000) {
    return _insightTokenCache.token
  }
  const res = await axios.get<{ token: string }>(`${API_URL}/auth/ws-token`)
  _insightTokenCache = { token: res.data.token, expiresAt: Date.now() + 25_000 }
  return res.data.token
}

async function agentHeaders(): Promise<Record<string, string>> {
  const token = await getAgentToken()
  return { 'Content-Type': 'application/json', 'Authorization': `Bearer ${token}` }
}

// ── AI-powered insights via Agent Server ──────────────────────────────────────

export async function generateInsights(stats: HomeStats): Promise<string[]> {
  try {
    const res = await fetch(`${AGENT_URL}/agents/insights/home`, {
      method: 'POST',
      headers: await agentHeaders(),
      body: JSON.stringify(stats),
    })
    if (!res.ok) return fallbackHomeInsights(stats)
    const data = await res.json()
    return Array.isArray(data) && data.length > 0 ? data : fallbackHomeInsights(stats)
  } catch {
    return fallbackHomeInsights(stats)
  }
}

function fallbackHomeInsights(stats: HomeStats): string[] {
  const insights: string[] = []
  if ((stats.conversationsOpen ?? 0) > 0) insights.push(`${stats.conversationsOpen} conversas abertas aguardando atendimento`)
  if ((stats.unassignedCount ?? 0) > 0) insights.push(`${stats.unassignedCount} conversas sem atendente atribuído`)
  if ((stats.newContactsThisWeek ?? 0) > 0) insights.push(`${stats.newContactsThisWeek} novos contatos esta semana`)
  if (insights.length === 0) insights.push('Nenhuma atividade recente')
  return insights.slice(0, 3)
}

export async function generateDashboardInsights(kpis: unknown[]): Promise<DashboardInsight[]> {
  try {
    const res = await fetch(`${AGENT_URL}/agents/insights/dashboard`, {
      method: 'POST',
      headers: await agentHeaders(),
      body: JSON.stringify({ kpis }),
    })
    if (!res.ok) return []
    const data = await res.json()
    return Array.isArray(data) ? data : []
  } catch {
    return []
  }
}

export async function generateCRMInsights(stats: CRMStats): Promise<DashboardInsight[]> {
  try {
    const res = await fetch(`${AGENT_URL}/agents/insights/crm`, {
      method: 'POST',
      headers: await agentHeaders(),
      body: JSON.stringify(stats),
    })
    if (!res.ok) return []
    const data = await res.json()
    return Array.isArray(data) ? data.slice(0, 2) : []
  } catch {
    return []
  }
}

export async function generateCampaignInsights(
  _campaignName: string, _stats: Record<string, unknown>, _churnBreakdown: Record<string, unknown>,
): Promise<CampaignInsight[]> {
  return []
}

export async function generateSessionTitle(userMessage: string): Promise<string> {
  return userMessage.slice(0, 40).trim() || 'Nova conversa'
}
